### ISSUE TITLE
Image attachments don't work when using confluence.update_page()

### ISSUE THREAD

**Issue by mistune** [iamjackg/md2cf#109]
But works when using md2cf from the command line. Here is the output from the update_page function

![image](https://github.com/iamjackg/md2cf/assets/37379471/f3de4d71-d377-4389-8ba1-b03577b4047f)

**Comment by iamjackg** [comment]
`update_page` only updates the page content, not the attachments. Those have to be uploaded separately using `create_attachment` or `update_attachment`.
