### ISSUE TITLE
updating attachments not allowed

### ISSUE THREAD

**Issue by timothybonci** [iamjackg/md2cf#15]
Currently the code for uploading attachments calls the Create Attachment method (https://developer.atlassian.com/cloud/confluence/rest/api-group-content---attachments/#api-wiki-rest-api-content-id-child-attachment-post), which does not allow updates, only the initial upload.

If instead we used the Create or Update Attachment method (https://developer.atlassian.com/cloud/confluence/rest/api-group-content---attachments/#api-wiki-rest-api-content-id-child-attachment-put), this should allow the same call to upsert the attachments instead.

**Comment by iamjackg** [comment]
Thank you so much for submitting this! I'll take a look at the MR and merge it :)
