### ISSUE TITLE
Idea: return page id when was created

### ISSUE THREAD

**Issue by ezequiel-aguilera-uala** [iamjackg/md2cf#20]
Idea: return the id of the page when it is created. And to be able to use this data.
(I'm using it from a bash script)

**Comment by iamjackg** [comment]
This makes sense, but it might require a little bit of thought. Would you want the ID just when a page is created, or also when it's updated?

**Comment by bhrutledge** [comment]
I think both would be helpful, and I'd take it a step further to show the full URL of the page.
