### ISSUE TITLE
certificate verify failed: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by kordia-mgnt** [iamjackg/md2cf#21]
[Possible solve Ref](https://community.atlassian.com/t5/Jira-questions/Python-script-fails-with-SSL-CERTIFICATE-VERIFY-FAILED/qaq-p/1410110)
```sh
md2cf --host 'https://confluence.********.com/rest/api' --username ************ --password '************' --space TEST document.md
ERROR: HTTPSConnectionPool(host='confluence.kordia.net', port=443): Max retries exceeded with url: /rest/api/content?title=md2cf+test&spaceKey=TEST (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
```

**Comment by iamjackg** [comment]
I added an `--insecure` flag that will skip SSL certificate validation. Can you try version `1.2.0` and let me know if it solves your problem?

**Comment by iamjackg** [comment]
Hey @kordia-mgnt, I'm gonna assume this is solved. If anything's wrong, feel free to open another issue!
