### ISSUE TITLE
Remove top-level header when used as page title

### ISSUE THREAD

**Issue by bhrutledge** [iamjackg/md2cf#26]
From my initial testing, it looks like a when the [page title](https://github.com/iamjackg/md2cf#page-title) is set using "the first top-level header found in the document (i.e. the first # header)", the title appears twice in Confluence: once at the top of the page, and again in the body. In that scenario, could it be removed during the rendering process?

Maybe here?

https://github.com/iamjackg/md2cf/blob/67ff786dbcb3b72da44ab141186d3fd2c50d011c/md2cf/confluence_renderer.py#L62-L66

**Comment by iamjackg** [comment]
Ah yeah that makes a lot of sense. I'll get to this in a few days: real life is keeping me busy :)

**Comment by iamjackg** [comment]
Hey, just letting you know that I'm going through a move, so I won't have time for the next little while. I haven't forgotten about this.

**Comment by iamjackg** [comment]
Just published this change in the latest version :)
