### ISSUE TITLE
Log in using Atlassian account ID

### ISSUE THREAD

**Issue by bosborne** [iamjackg/md2cf#3]
Looks like there's been a major change in the API:

https://developer.atlassian.com/cloud/confluence/deprecation-notice-user-privacy-api-migration-guide/

I've been having trouble logging in using username, it might be related to this change, but I'm not entirely certain.

**Comment by bosborne** [comment]
I'm going to close this issue, given that there are other explanations.

**Comment by iamjackg** [comment]
Glad I could help! :laughing:
