### ISSUE TITLE
Feature Request: Add labels to published pages

### ISSUE THREAD

**Issue by jannismain** [iamjackg/md2cf#41]
Extend yaml frontmatter parsing to read `labels` key:

```md
---
title: Page Title
labels: [label1, label2]
---
...
```

Apply those labels to confluence page after creation. When updating pages, I would probably delete existing labels from the page and apply those listed in yaml frontmatter, to ensure they are in sync with the labels listed in the markdown file.

**Comment by jannismain** [comment]
For my personal markdown writing preference, I would also like to support listing labels in the document like this

```md
# Page Title

#label1 #label2

This page has labels.
```

However, this is custom markdown syntax. How do you feel about introducing support for something like this in `md2cf`?

**Comment by iamjackg** [comment]
Custom markdown syntax is kinda messy with Mistune, it's something we could consider in the future, but for now I'd rather keep these in the frontmatter if that's okay.
