### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by AndzheyAsryan** [iamjackg/md2cf#47]
Hello.

I'm trying to publish a test page to the Confluence using the tool. The command looks like this, plus username and password of course.
```
md2cf -o https://jayconfluence.atlassian.net -s MARKDOWN test.md
```
As a result I'm getting the 404 page, mentioning that the following URL is not found:
https://jayconfluence.atlassian.net/content?title=Markdown+Syntax&spaceKey=MARKDOWN

Indeed, if I go there - it is not found. The URL to the existing page looks like this:
https://jayconfluence.atlassian.net/wiki/spaces/MARKDOWN/pages/262145/Markdown+Syntax

I get the same trying to create non-existent page. Interestingly, I also get the same response if I provide wrong password, for example.

Did the URL change or am I doing something wrong?

Thanks in advance!

**Comment by iamjackg** [comment]
Hey! You actually need to also specify the path to the REST API as part of the host parameter. I'm not sure what that is for Atlassian-hosted instances, but for self-hosted Confluence instances it's at `/rest/api`, so a full URL would look like this: `https://confluence.example.com/rest/api`.

**Comment by AndzheyAsryan** [comment]
Hi, @iamjackg , thanks for your response!

Does it mean I have to use `https://jayconfluence.atlassian.net/wiki/spaces` instead of just `https://jayconfluence.atlassian.net` in the `--host` value, in my case?

**Comment by iamjackg** [comment]
Judging from [this](https://developer.atlassian.com/cloud/confluence/rest/v1/intro/#status-code) it seems like it should be `https://jayconfluence.atlassian.net/wiki/rest/api`

Let me know if that works!
