### ISSUE TITLE
Support "minorEdit" option

### ISSUE THREAD

**Issue by jannismain** [iamjackg/md2cf#49]
The confluence API supports the "minorEdit" option to not notify watchers when a page has been updated.

I would like to reduce the number of e-mails generated by automatically updating several pages at once, so I've implemented this for the `update_page` handler in #50 .

**Comment by jannismain** [comment]
Implemented in #50

**Comment by iamjackg** [comment]
Hey, I just pushed an alpha version of v2 -- it has some breaking changes in the output format (https://github.com/iamjackg/md2cf/tree/develop#terminal-output-format), and it includes your changes for this. Can you give it a whirl and let me know if it's fine?

It's at https://pypi.org/project/md2cf/2.0.0a0/ and you can install it with

```bash
pip install md2cf --pre
```
