### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by beatzuerrer** [iamjackg/md2cf#54]
I don't know if it's a md2cf or my problem. I have several md's with umlauts (äöü etc.). These are not converted correctly.
Can I fix this somewhere?
I am unfortunately not a gifted Python programmer

**Comment by iamjackg** [comment]
Hey there! I was actually discussing something similar in #51 where another user was running into something similar. Would you mind trying the code snippet I posted there, and letting me know the results? Thanks!

**Comment by iamjackg** [comment]
Hey, I just pushed an alpha version of v2 -- it has some breaking changes in the output format (https://github.com/iamjackg/md2cf/tree/develop#terminal-output-format), but it includes a fix for this issue: it tries to autodetect the encoding if the default fails. Can you give it a whirl and let me know if it's fine?

It's at https://pypi.org/project/md2cf/2.0.0a0/ and you can install it with

```bash
pip install md2cf --pre
```

**Comment by iamjackg** [comment]
[v2.0.0](https://github.com/iamjackg/md2cf/releases/tag/v2.0.0) is out :) Closing this.
