### ISSUE TITLE
Handle relative-links within documents 

### ISSUE THREAD

**Issue by mschmieder** [iamjackg/md2cf#55]
Hello,

I just looked at your project and it does seem to be super-promising for the use-case I have. One of the features that I am missing it the ability to handle relative links within the Markdown files. In the past I tried another tools and provided a pull-request for that functionality, but there have been a few issues with the implementation. Please have a look here for reference:

https://github.com/justmiles/go-markdown2confluence/pull/40

Doing this in Python does sound way more straight forward and sustainable and I was wondering if you had already something in store or maybe an idea on how this could be implemented.

Feature-wise it would be something like

- Identify relative paths within the document
- Replace the paths with the Confluence pages
- Create the Confluence page if it does not already exist

I'd be happy to help out!

Best,
Matthias

**Comment by iamjackg** [comment]
Hey, I just pushed an alpha version of v2 -- it has some breaking changes in the output format (https://github.com/iamjackg/md2cf/tree/develop#terminal-output-format), but it includes a rework of your changes to support this. Can you give it a whirl and let me know if it's fine?

It's at https://pypi.org/project/md2cf/2.0.0a0/ and you can install it with

```bash
pip install md2cf --pre
```

**Comment by iamjackg** [comment]
[v2.0.0](https://github.com/iamjackg/md2cf/releases/tag/v2.0.0) is out :) Closing this.
