### ISSUE TITLE
parent_title and rate limits

### ISSUE THREAD

**Issue by Pixie-Axerup** [iamjackg/md2cf#59]
Hi! 
I really like md2cf! Awesome! I created a small simple Github Action for syncing Github md-files to Confluence in my company, and it works really well. The use of it started spreading to other teams, and some issues surfaced :-) 

1. it says you can use either parent_id or parent_title, but I can't get parent_title to work. it says `Unexpected input(s) 'parent_title', valid inputs are ['entryPoint', 'args', 'github_f', 'space', 'confluence_token', 'confluence_host', 'parent_id']` and I don't think it's due to something I did... but maybe I'm mistaken. I looked in the api.py and I can't find any reference to parent_title.

2. A team that has many md-files to sync ran into rate limiting issues when trying to sync them. It is due to the Confluence rate limiting settings in our company off course (and we are trying to increase that limit), but I did some googling and came across this: https://confluence.atlassian.com/doc/adjusting-your-code-for-rate-limiting-992679008.html
Any thought on adding something like this in your code for the "micro-implementation" of the ConfluenceServer REST API?

I can provide source code if needed. Otherwise just happy for some thoughts on above issues :-) 
Thanks
/Pixie

**Comment by iamjackg** [comment]
Hey! I'm actually working on a pretty big update these days. I'll definitely look into 1, because it should not be happening :) 2 will require some more work, but might be worth adding. Stay tuned!

**Comment by Pixie-Axerup** [comment]
Hi! That sounds interesting! I will stay tuned! :-)

**Comment by iamjackg** [comment]
Hey! I think issue 1 might actually be on your end: the error message you posted is from GitHub Actions, not md2cf. It looks like you're trying to pass `parent_title` to an action that I assume was written by you guys, and it probably doesn't support it as an input. When using md1cf, it's specified through the `--parent-title` command line parameter, e.g.

```bash
md2cf --parent-title "Parent page" file.md
```

**Comment by iamjackg** [comment]
Ah, I see there's an `args` input in your error message, which seems to imply that your action can take custom arguments! That's probably a clue, but it's entirely dependent on how your action works :)

**Comment by iamjackg** [comment]
Sorry about all the comments, just going through your points one by one :) The second request might take a bit longer than I hoped, because the library I'm using to wrap the Confluence API doesn't support accessing headers in the response. I might have to switch back to plain `requests`, which is something I should probably do anyway since Tortilla, the current library, hasn't been updated since 2018.

**Comment by Pixie-Axerup** [comment]
Hi! About the parent_title: ok, I will investigate on my end a bit more then... 

About the 2nd one: thanks for the update! We just ran into the problem and when I saw it was actually possible from a confluence perspective, I wanted to share it! Fingers crossed that you might have the possibility to do it sometime in the future!

**Comment by iamjackg** [comment]
Hey, I just pushed an alpha version of v2 -- it has some breaking changes in the output format (https://github.com/iamjackg/md2cf/tree/develop#terminal-output-format), but includes a fix for this issue. Can you give it a whirl and let me know if it's fine?

It's at https://pypi.org/project/md2cf/2.0.0a0/ and you can install it with

```bash
pip install md2cf --pre
```
