### ISSUE TITLE
Relative links break with a hash (#) to sub-section

### ISSUE THREAD

**Issue by jimstein3d** [iamjackg/md2cf#77]
Markdown reference to section from another (slask.md) file will not work after import to Confluence.
slask.md contains:
```
#  Main section

##  [sub-section](./child.md#sub-section)    
##  [sub-section](/child.md#sub-section)
##  [sub-section](child.md#sub-section)
```
This will result in broken links i confluence.

(/child.md#sub-section) results in a link like this https:///\<my-secret\>.atlassian.net/child.md#sub-section

Edit: out problem seem to be that urlparse.urlparse(link) marks sub-section as a fragment and then dont create a replacement_link.

**Comment by iamjackg** [comment]
This is released!
