### ISSUE TITLE
.pages file at top (root) level

### ISSUE THREAD

**Issue by galund** [iamjackg/md2cf#90]
I'd like to be able to specify a pages file at the top level. This is useful in the following scenario:

I have two folders A and B, both containing markdown files, both containing links to each other.

I wish to process A and B into folders ie there should be a parent page for A, and a parent page for B.

Because there are relative links between A and B, A and B must be processed in a single run. The `--parent-title` option doesn't help because the files from A and from B would be mixed underneath a single parent page.

If A and B are specified on the command line, the `.pages` files are ignored, because A and B are currently processed as separate "root level" directories.

I cannot specify the real root of A and B, because that would pull in additional directories and markdown files that aren't desired.

I have a proposed fix for this issue which I'll reference shortly...

**Comment by iamjackg** [comment]
Your use case makes perfect sense! Will check the MR. :)

**Comment by iamjackg** [comment]
Closed by #91. Thanks!
