### ISSUE TITLE
Link parsing fails for document references

### ISSUE THREAD

**Issue by mschmieder** [iamjackg/md2cf#96]
Hi,

I just noticed that it's not possible to use `md2cf` anymore with document references like table of contents, since the relative path detector detects the paths that start with `#`

```md
[Frequently Asked Questions](#frequently-asked-questions-osep)
```

Having something like this in the document results in 

```
Page test.md has a relative link to , which is not in the list of pages to be uploaded.  
```

**Comment by iamjackg** [comment]
Thanks for reporting this -- I'll take a look!
